### ISSUE TITLE
插件貌似失效了

### ISSUE THREAD

**Issue by LiQing-Code** [extremeblackliu/VRChatMultiLanguage#1]
我把version.dll以及语言文件复制到了VRChat的根目录。
![image](https://user-images.githubusercontent.com/51829935/172272589-63a7eb64-4da7-4433-a5ea-0b9d77e5ad08.png)

但是启动游戏并没有效果😵
VRChat版本：**w_2022.2.1p4-e6e786a7eb**

**Comment by LiQing-Code** [comment]
插件没有失效，需要把”Language_CN.json“改成"Language.json",快捷菜单没有汉化，展开大菜单后有汉化

**Comment by extremeblackliu** [comment]
由于插件不是太受国人欢迎，我没有再做进一步更新了，我建议你使用MelonLoader版本的，最后测试是稳定汉化，参阅:https://github.com/extremeblackliu/VRChat-ModuleLoader-Csharp

**Comment by LiQing-Code** [comment]
> 

感谢回复，我会试试MelonLoader版本的
